/**
 * The State category list -- taken from the content team's State Government
 * Exams doc (see scripts/exam-mapping/retag_state_exams.mjs). Offered in the
 * exam editor's Category dropdown when Level is State, and never shares a name
 * with the Central list (centralExamCategories.js). Names must match
 * lc_exam_categories.name exactly. Regenerate by re-running that script.
 */
export const STATE_EXAM_CATEGORIES = [
  "ABHAD Constable",
  "Accounts Services",
  "Administrative Services",
  "Agriculture",
  "Agriculture Department",
  "Agriculture Services",
  "Agriculture Supervisor",
  "Animal Husbandry",
  "Armed Police",
  "Class III Posts",
  "Cooperative Banking",
  "Cooperative Services",
  "Drug Control",
  "Education Services",
  "Emergency Services",
  "Enforcement",
  "Engineering",
  "Engineering Services",
  "Excise",
  "Excise Services",
  "Finance Service",
  "Fire Services",
  "Fisheries",
  "Food Safety",
  "Forest Guard",
  "Forest Services",
  "Grade III/IV Posts",
  "Group B Services",
  "Group B/C",
  "Group B/C Clerk",
  "Group B/C Posts",
  "Group C",
  "Group C Posts",
  "Group C Services",
  "Group C/D Posts",
  "Group D",
  "Group D Services",
  "Group I Services",
  "Group II Services",
  "Group III Posts",
  "Group III Services",
  "Group IV Posts",
  "Group IV Services",
  "Group Posts",
  "Health CHO",
  "Health Nursing",
  "Health Pharma",
  "Health Services",
  "High Court Clerk",
  "High Court Jr Asst",
  "Higher Education",
  "Home Guard",
  "Home Guard Services",
  "Horticulture",
  "Hostel Management",
  "Intelligence SI",
  "IT Services",
  "Jail Services",
  "JE Engineering",
  "Judicial Services",
  "Junior Scale Officer",
  "Labour Services",
  "Law Service",
  "Lecturer",
  "Legal Metrology",
  "Library Services",
  "Master Cadre",
  "Medical Officer",
  "Medical Services",
  "MPW",
  "NHM Health",
  "Other Technical Posts",
  "Panchayat",
  "Panchayat Raj Services",
  "Panchayat Services",
  "Panchayat/Rural Development",
  "Pharma Services",
  "Police Constable",
  "Police Recruitment",
  "Police Services",
  "Police SI",
  "Postal GDS",
  "Revenue",
  "Revenue Land",
  "Revenue Services",
  "Rural Banking",
  "Rural Development",
  "School Education",
  "Secretarial Services",
  "Social Services",
  "Social Welfare Services",
  "Soil Conservation",
  "State Civil Services",
  "Storekeeper",
  "Teacher Eligibility",
  "Teacher Recruitment",
  "Technical Services",
  "TET Primary",
  "TET Upper Primary",
  "Transport Services",
  "Veterinary",
  "Veterinary Services"
];
