/**
 * The UT category list -- taken from the content team's UT Exams List doc
 * (see scripts/exam-mapping/retag_ut_exams.mjs). Offered in the exam editor's
 * Category dropdown when Level is UT. Never shares a name with the Central or
 * State lists: a doc name that would collide carries a " (UT)" suffix. Names
 * must match lc_exam_categories.name exactly. Regenerate by re-running that
 * script.
 */
export const UT_EXAM_CATEGORIES = [
  "Accounts",
  "Administration",
  "Administrative",
  "Agriculture (UT)",
  "Animal Husbandry (UT)",
  "Banking (UT)",
  "Census Operations",
  "Central Govt",
  "Civil Security",
  "Defence (UT)",
  "Disaster",
  "Disaster Management",
  "Disaster Response",
  "Election Management",
  "Electricity",
  "Engineering (UT)",
  "Engineering Services (UT)",
  "Environment",
  "Excise (UT)",
  "Excise & Taxation",
  "Fire Services (UT)",
  "Fisheries (UT)",
  "Food",
  "Food & Civil Supplies",
  "Food & Supplies",
  "Forest",
  "Forest & Wildlife",
  "Health",
  "Hill Council",
  "Home Guards",
  "Housing",
  "Judiciary",
  "Marine",
  "Marine Services",
  "Medical",
  "Metro",
  "Municipal",
  "Municipal Admin",
  "Municipal Engineering",
  "Municipal Health",
  "Panchayat (UT)",
  "Police (UT)",
  "Ports",
  "Ports & Shipping",
  "Postal",
  "Power",
  "Power Utilities",
  "Prison Services",
  "Professional Entrance",
  "Public Works",
  "Research",
  "Revenue (UT)",
  "Rural Development (UT)",
  "Shipping",
  "Social Welfare",
  "Sports",
  "SSC (UT)",
  "Teaching",
  "Tourism",
  "Transport",
  "Utilities",
  "Water",
  "Water Engineering",
  "Water Supply"
];
