
-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.quizzes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  title character varying NOT NULL,
  description text,
  subject character varying,
  category character varying,
  source_file character varying,
  total_questions integer,
  is_freemium boolean DEFAULT false,
  is_locked boolean DEFAULT true,
  unlock_cost integer DEFAULT 0,
  file_hash character varying,
  created_at timestamp with time zone DEFAULT now(),
  exam_name character varying,
  conducting_body character varying,
  website_url character varying,
  thumbnail_url character varying,
  level text,
  state_ut text,
  details text,
  lc_exam_id uuid,
  playable_questions integer,
  CONSTRAINT quizzes_pkey PRIMARY KEY (id),
  CONSTRAINT quizzes_lc_exam_id_fkey FOREIGN KEY (lc_exam_id) REFERENCES public.lc_exams(id)
);
CREATE TABLE public.questions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  quiz_id uuid NOT NULL,
  question_number integer,
  question_text text NOT NULL,
  options jsonb,
  correct_answer character varying,
  explanation text,
  created_at timestamp with time zone DEFAULT now(),
  review_flags ARRAY NOT NULL DEFAULT '{}'::text[],
  CONSTRAINT questions_pkey PRIMARY KEY (id),
  CONSTRAINT questions_quiz_id_fkey FOREIGN KEY (quiz_id) REFERENCES public.quizzes(id)
);
CREATE TABLE public.user_profiles (
  id uuid NOT NULL,
  email text,
  full_name text,
  rank text,
  service_branch text,
  years_of_service integer,
  education_level text,
  board text,
  percentage numeric,
  height_cm integer,
  weight_kg integer,
  chest_cm integer,
  regiment text,
  trade text,
  medals text,
  discharge_type text,
  preferred_states jsonb DEFAULT '[]'::jsonb,
  preferred_sectors jsonb DEFAULT '[]'::jsonb,
  preferred_job_types jsonb DEFAULT '[]'::jsonb,
  skills jsonb DEFAULT '{}'::jsonb,
  veer_score integer DEFAULT 0,
  consent_given boolean DEFAULT false,
  consent_timestamp timestamp with time zone,
  profiling_completed boolean DEFAULT false,
  raw_profile_data jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  recommendations jsonb DEFAULT '[]'::jsonb,
  avatar_url text,
  subscription_tier text DEFAULT 'FREE'::text,
  subscription_expires_at timestamp with time zone,
  subscription_started_at timestamp with time zone,
  subscription_id text,
  payment_id text,
  free_quiz_used boolean DEFAULT false,
  cv_generated boolean DEFAULT false,
  points_balance integer NOT NULL DEFAULT 0,
  points_lifetime integer NOT NULL DEFAULT 0,
  CONSTRAINT user_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT user_profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.quiz_attempts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  quiz_id uuid NOT NULL,
  quiz_title text NOT NULL DEFAULT ''::text,
  quiz_subject text,
  quiz_category text,
  total_questions integer NOT NULL DEFAULT 0,
  answered_questions integer NOT NULL DEFAULT 0,
  correct_answers integer NOT NULL DEFAULT 0,
  wrong_answers integer NOT NULL DEFAULT 0,
  skipped_questions integer NOT NULL DEFAULT 0,
  score_percent numeric NOT NULL DEFAULT 0,
  time_taken_seconds integer NOT NULL DEFAULT 0,
  answers jsonb NOT NULL DEFAULT '{}'::jsonb,
  completed_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT quiz_attempts_pkey PRIMARY KEY (id),
  CONSTRAINT quiz_attempts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id),
  CONSTRAINT quiz_attempts_quiz_id_fkey FOREIGN KEY (quiz_id) REFERENCES public.quizzes(id)
);
CREATE TABLE public.exams (
  exam_id character varying NOT NULL,
  exam_name character varying NOT NULL,
  conducting_body character varying,
  career_track character varying,
  priority integer DEFAULT 1,
  frequency character varying,
  state_ut character varying,
  is_state_specific boolean DEFAULT false,
  base_url character varying,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  region_id uuid,
  conducting_body_id uuid,
  subject_requirements jsonb,
  logo_path text,
  content_completeness jsonb,
  thumbnail_subject text,
  has_hindi_subject boolean,
  CONSTRAINT exams_pkey PRIMARY KEY (exam_id),
  CONSTRAINT exams_region_id_fkey FOREIGN KEY (region_id) REFERENCES public.lc_regions(id),
  CONSTRAINT exams_conducting_body_id_fkey FOREIGN KEY (conducting_body_id) REFERENCES public.lc_conducting_bodies(id)
);
CREATE TABLE public.jobs (
  job_id integer NOT NULL DEFAULT nextval('jobs_job_id_seq'::regclass),
  exam_id character varying,
  title character varying NOT NULL,
  url character varying UNIQUE,
  published_on timestamp with time zone,
  last_date timestamp with time zone,
  vacancies integer,
  age_range character varying,
  raw_json jsonb,
  created_at timestamp with time zone DEFAULT now(),
  lc_exam_id uuid,
  career_track text,
  tags ARRAY DEFAULT '{}'::text[],
  is_expired boolean DEFAULT false,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT jobs_pkey PRIMARY KEY (job_id),
  CONSTRAINT jobs_exam_id_fkey FOREIGN KEY (exam_id) REFERENCES public.exams(exam_id),
  CONSTRAINT jobs_lc_exam_id_fkey FOREIGN KEY (lc_exam_id) REFERENCES public.lc_exams(id)
);
CREATE TABLE public.user_notifications (
  id integer NOT NULL DEFAULT nextval('user_notifications_id_seq'::regclass),
  user_id uuid NOT NULL,
  job_id integer,
  message text NOT NULL,
  is_read boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_notifications_pkey PRIMARY KEY (id),
  CONSTRAINT user_notifications_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.jobs(job_id)
);
CREATE TABLE public.resources (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  resource_id character varying NOT NULL UNIQUE,
  file_hash character varying,
  source_file character varying,
  title character varying NOT NULL,
  exam_name character varying,
  subject character varying,
  category character varying CHECK (category::text = ANY (ARRAY['Intro'::character varying, 'Guide'::character varying, 'Precis'::character varying]::text[])),
  conducting_body character varying,
  website_url character varying,
  chapter_count integer DEFAULT 0,
  storage_base_url character varying,
  metadata_url character varying,
  thumbnail_url character varying,
  is_freemium boolean DEFAULT false,
  is_locked boolean DEFAULT true,
  unlock_cost integer DEFAULT 0,
  status character varying DEFAULT 'Draft'::character varying CHECK (status::text = ANY (ARRAY['Draft'::character varying, 'In Review'::character varying, 'Published'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  format text NOT NULL DEFAULT 'html'::text CHECK (format = ANY (ARRAY['html'::text, 'blocks'::text])),
  level text,
  state_ut text,
  reader_theme_id text,
  subject_accent text,
  CONSTRAINT resources_pkey PRIMARY KEY (id)
);
CREATE TABLE public.employer_profiles (
  id uuid NOT NULL,
  company_name text NOT NULL,
  website text,
  contact_name text NOT NULL,
  designation text,
  industry text,
  location text,
  about text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  avatar_url text,
  CONSTRAINT employer_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT employer_profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.connections (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  sender_id uuid NOT NULL,
  receiver_id uuid NOT NULL,
  status text NOT NULL CHECK (status = ANY (ARRAY['pending'::text, 'accepted'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT connections_pkey PRIMARY KEY (id),
  CONSTRAINT connections_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES auth.users(id),
  CONSTRAINT connections_receiver_id_fkey FOREIGN KEY (receiver_id) REFERENCES auth.users(id)
);
CREATE TABLE public.chat_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  sender_id uuid NOT NULL,
  receiver_id uuid NOT NULL,
  content text,
  file_url text,
  file_name text,
  file_type text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT chat_messages_pkey PRIMARY KEY (id),
  CONSTRAINT chat_messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES auth.users(id),
  CONSTRAINT chat_messages_receiver_id_fkey FOREIGN KEY (receiver_id) REFERENCES auth.users(id)
);
CREATE TABLE public.lc_regions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  level text NOT NULL CHECK (level = ANY (ARRAY['central'::text, 'state'::text, 'ut'::text])),
  name text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT lc_regions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.lc_conducting_bodies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  website text,
  logo_path text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT lc_conducting_bodies_pkey PRIMARY KEY (id)
);
CREATE TABLE public.lc_thumbnail_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  background_image_path text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT lc_thumbnail_templates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.lc_exams (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  conducting_body_id uuid NOT NULL,
  region_id uuid NOT NULL,
  category text,
  name text NOT NULL,
  website text,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'published'::text, 'archived'::text])),
  thumbnail_template_id uuid,
  accent_color text,
  also_listed_as jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  thumbnail_subject text,
  category_detail text,
  has_hindi_subject boolean,
  CONSTRAINT lc_exams_pkey PRIMARY KEY (id),
  CONSTRAINT lc_exams_conducting_body_id_fkey FOREIGN KEY (conducting_body_id) REFERENCES public.lc_conducting_bodies(id),
  CONSTRAINT lc_exams_region_id_fkey FOREIGN KEY (region_id) REFERENCES public.lc_regions(id),
  CONSTRAINT lc_exams_thumbnail_template_id_fkey FOREIGN KEY (thumbnail_template_id) REFERENCES public.lc_thumbnail_templates(id)
);
CREATE TABLE public.lc_tags (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  CONSTRAINT lc_tags_pkey PRIMARY KEY (id)
);
CREATE TABLE public.lc_exam_tags (
  exam_id uuid NOT NULL,
  tag_id uuid NOT NULL,
  CONSTRAINT lc_exam_tags_pkey PRIMARY KEY (exam_id, tag_id),
  CONSTRAINT lc_exam_tags_exam_id_fkey FOREIGN KEY (exam_id) REFERENCES public.lc_exams(id),
  CONSTRAINT lc_exam_tags_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES public.lc_tags(id)
);
CREATE TABLE public.lc_exam_legacy_map (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  lc_exam_id uuid NOT NULL,
  legacy_exam_id text NOT NULL,
  match_method text NOT NULL CHECK (match_method = ANY (ARRAY['exact'::text, 'normalized_exact'::text, 'normalized_exact_cb'::text, 'normalized_exact_region'::text, 'fuzzy'::text])),
  match_confidence numeric,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT lc_exam_legacy_map_pkey PRIMARY KEY (id),
  CONSTRAINT lc_exam_legacy_map_lc_exam_id_fkey FOREIGN KEY (lc_exam_id) REFERENCES public.lc_exams(id)
);
CREATE TABLE public.lc_exam_resource_map (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  exam_id uuid NOT NULL,
  resource_id text NOT NULL,
  category text NOT NULL CHECK (category = ANY (ARRAY['Intro'::text, 'Guide'::text, 'Precis'::text, 'PYQ'::text])),
  confidence text NOT NULL CHECK (confidence = ANY (ARRAY['high'::text, 'medium'::text, 'low'::text])),
  reasoning text,
  source text NOT NULL DEFAULT 'gemini'::text CHECK (source = ANY (ARRAY['gemini'::text, 'manual'::text, 'exact_name'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT lc_exam_resource_map_pkey PRIMARY KEY (id),
  CONSTRAINT lc_exam_resource_map_exam_id_fkey FOREIGN KEY (exam_id) REFERENCES public.lc_exams(id)
);
CREATE TABLE public.pyq_papers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  exam_name text,
  subject text,
  conducting_body text,
  website_url text,
  total_questions integer NOT NULL DEFAULT 0,
  source_file text,
  file_hash text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  level text,
  state_ut text,
  details text,
  lc_exam_id uuid,
  CONSTRAINT pyq_papers_pkey PRIMARY KEY (id),
  CONSTRAINT pyq_papers_lc_exam_id_fkey FOREIGN KEY (lc_exam_id) REFERENCES public.lc_exams(id)
);
CREATE TABLE public.pyq_questions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  paper_id uuid NOT NULL,
  question_number integer NOT NULL,
  question_text text NOT NULL,
  options jsonb NOT NULL,
  correct_answer text,
  explanation text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pyq_questions_pkey PRIMARY KEY (id),
  CONSTRAINT pyq_questions_paper_id_fkey FOREIGN KEY (paper_id) REFERENCES public.pyq_papers(id)
);
CREATE TABLE public.lc_exam_intro (
  exam_id uuid NOT NULL,
  resource_id text,
  manual_title text,
  manual_body text,
  source text NOT NULL CHECK (source = ANY (ARRAY['auto'::text, 'manual'::text, 'unset'::text])),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT lc_exam_intro_pkey PRIMARY KEY (exam_id),
  CONSTRAINT lc_exam_intro_exam_id_fkey FOREIGN KEY (exam_id) REFERENCES public.lc_exams(id)
);
CREATE TABLE public.ps_candidate_profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  path text NOT NULL CHECK (path = ANY (ARRAY['operational'::text, 'professional'::text])),
  work_types ARRAY NOT NULL DEFAULT '{}'::text[],
  skills ARRAY NOT NULL DEFAULT '{}'::text[],
  preferred_locations jsonb NOT NULL DEFAULT '[]'::jsonb,
  licences_qualifications ARRAY NOT NULL DEFAULT '{}'::text[],
  availability text,
  other_preferences text,
  profile_completed boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  sectors ARRAY NOT NULL DEFAULT '{}'::text[],
  tags ARRAY NOT NULL DEFAULT '{}'::text[],
  service text CHECK (service = ANY (ARRAY['Indian Army'::text, 'Indian Navy'::text, 'Indian Air Force'::text])),
  service_category text,
  branch text,
  trade text,
  rank text,
  service_years text,
  trade_proficiency text,
  duties ARRAY DEFAULT '{}'::text[],
  team_size_supervised integer DEFAULT 0,
  highest_working_level text,
  civil_licences jsonb DEFAULT '[]'::jsonb,
  consent_masked boolean DEFAULT true,
  consent_contact boolean DEFAULT true,
  CONSTRAINT ps_candidate_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT ps_candidate_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.ps_verifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  service_number text NOT NULL,
  document_path text NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'verified'::text, 'rejected'::text])),
  reviewed_by text,
  reviewed_at timestamp with time zone,
  rejection_reason text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ps_verifications_pkey PRIMARY KEY (id),
  CONSTRAINT ps_verifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.ps_job_requirements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employer_id uuid NOT NULL,
  role_titles ARRAY NOT NULL DEFAULT '{}'::text[],
  quantity integer NOT NULL CHECK (quantity > 0),
  locations ARRAY NOT NULL DEFAULT '{}'::text[],
  salary_range text,
  description text,
  jd_document_path text,
  requirements_text text,
  status text NOT NULL DEFAULT 'submitted'::text CHECK (status = ANY (ARRAY['submitted'::text, 'under_review'::text, 'approved'::text, 'rejected'::text, 'filled'::text, 'closed'::text])),
  hr_notes text,
  reviewed_by text,
  reviewed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  sector text,
  tags ARRAY NOT NULL DEFAULT '{}'::text[],
  job_family text,
  essential_capabilities ARRAY DEFAULT '{}'::text[],
  desired_capabilities ARRAY DEFAULT '{}'::text[],
  min_team_supervised integer DEFAULT 0,
  required_licences ARRAY DEFAULT '{}'::text[],
  experience_band text,
  shift_pattern text,
  bridge_training_available boolean DEFAULT false,
  relocation_support boolean DEFAULT false,
  service_preference text DEFAULT 'All'::text,
  CONSTRAINT ps_job_requirements_pkey PRIMARY KEY (id),
  CONSTRAINT ps_job_requirements_employer_id_fkey FOREIGN KEY (employer_id) REFERENCES public.employer_profiles(id)
);
CREATE TABLE public.ps_candidate_interest (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  requirement_id uuid NOT NULL,
  user_id uuid NOT NULL,
  pipeline_status text NOT NULL DEFAULT 'new'::text CHECK (pipeline_status = ANY (ARRAY['new'::text, 'hr_reviewing'::text, 'shortlisted'::text, 'candidate_contacted'::text, 'employer_contacted'::text, 'interview'::text, 'offer'::text, 'joined'::text, 'not_selected'::text, 'withdrawn'::text])),
  hr_notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ps_candidate_interest_pkey PRIMARY KEY (id),
  CONSTRAINT ps_candidate_interest_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT ps_candidate_interest_requirement_id_fkey FOREIGN KEY (requirement_id) REFERENCES public.ps_job_requirements(id)
);
CREATE TABLE public.ps_notification_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  event_type text NOT NULL,
  channel text NOT NULL DEFAULT 'whatsapp'::text,
  subject text NOT NULL,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  related_requirement_id uuid,
  related_user_id uuid,
  related_interest_id uuid,
  recipient text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'sent'::text, 'failed'::text, 'simulated'::text])),
  provider_response text,
  sent_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  recipient_count integer DEFAULT 1,
  CONSTRAINT ps_notification_events_pkey PRIMARY KEY (id),
  CONSTRAINT ps_notification_events_related_requirement_id_fkey FOREIGN KEY (related_requirement_id) REFERENCES public.ps_job_requirements(id),
  CONSTRAINT ps_notification_events_related_user_id_fkey FOREIGN KEY (related_user_id) REFERENCES auth.users(id),
  CONSTRAINT ps_notification_events_related_interest_id_fkey FOREIGN KEY (related_interest_id) REFERENCES public.ps_candidate_interest(id)
);
CREATE TABLE public.jobs_v2 (
  job_id integer NOT NULL DEFAULT nextval('jobs_v2_job_id_seq'::regclass),
  exam_id character varying,
  title character varying NOT NULL,
  url character varying UNIQUE,
  published_on timestamp with time zone,
  last_date timestamp with time zone,
  vacancies integer,
  age_range character varying,
  raw_json jsonb,
  created_at timestamp with time zone DEFAULT now(),
  lc_exam_id uuid,
  career_track text,
  tags ARRAY DEFAULT '{}'::text[],
  is_expired boolean DEFAULT false,
  updated_at timestamp with time zone DEFAULT now(),
  ai_description text,
  CONSTRAINT jobs_v2_pkey PRIMARY KEY (job_id),
  CONSTRAINT jobs_v2_exam_id_fkey FOREIGN KEY (exam_id) REFERENCES public.exams(exam_id),
  CONSTRAINT jobs_v2_lc_exam_id_fkey FOREIGN KEY (lc_exam_id) REFERENCES public.lc_exams(id)
);
CREATE TABLE public.user_exam_targets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  exam_id uuid NOT NULL,
  is_primary boolean NOT NULL DEFAULT false,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'paused'::text, 'completed'::text])),
  target_date date,
  started_at timestamp with time zone NOT NULL DEFAULT now(),
  last_activity_at timestamp with time zone,
  CONSTRAINT user_exam_targets_pkey PRIMARY KEY (id),
  CONSTRAINT user_exam_targets_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT user_exam_targets_exam_id_fkey FOREIGN KEY (exam_id) REFERENCES public.lc_exams(id)
);
CREATE TABLE public.user_resource_reads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  resource_id text NOT NULL,
  exam_id uuid,
  subject_key text,
  status text NOT NULL DEFAULT 'not_started'::text CHECK (status = ANY (ARRAY['not_started'::text, 'in_progress'::text, 'completed'::text])),
  opened_at timestamp with time zone,
  completed_at timestamp with time zone,
  time_spent_sec integer,
  CONSTRAINT user_resource_reads_pkey PRIMARY KEY (id),
  CONSTRAINT user_resource_reads_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT user_resource_reads_exam_id_fkey FOREIGN KEY (exam_id) REFERENCES public.lc_exams(id)
);
CREATE TABLE public.user_quiz_attempts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  quiz_id uuid NOT NULL,
  exam_id uuid,
  subject_key text,
  score_pct double precision,
  questions_total integer,
  questions_correct integer,
  attempted_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_quiz_attempts_pkey PRIMARY KEY (id),
  CONSTRAINT user_quiz_attempts_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT user_quiz_attempts_exam_id_fkey FOREIGN KEY (exam_id) REFERENCES public.lc_exams(id)
);
CREATE TABLE public.lc_exam_quiz_map (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  exam_id uuid NOT NULL,
  quiz_id uuid NOT NULL,
  confidence text NOT NULL CHECK (confidence = ANY (ARRAY['high'::text, 'medium'::text, 'low'::text])),
  reasoning text,
  source text NOT NULL DEFAULT 'gemini'::text CHECK (source = ANY (ARRAY['gemini'::text, 'manual'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT lc_exam_quiz_map_pkey PRIMARY KEY (id),
  CONSTRAINT lc_exam_quiz_map_exam_id_fkey FOREIGN KEY (exam_id) REFERENCES public.lc_exams(id)
);
CREATE TABLE public.point_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  action_code text NOT NULL,
  points integer NOT NULL,
  ref_table text,
  ref_id text,
  idempotency_key text NOT NULL,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT point_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT point_transactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.rewards (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  sku text NOT NULL UNIQUE,
  name text NOT NULL,
  description text,
  category text,
  points_cost integer NOT NULL,
  image_url text,
  requires_size boolean NOT NULL DEFAULT false,
  available_sizes ARRAY,
  stock_quantity integer,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT rewards_pkey PRIMARY KEY (id)
);
CREATE TABLE public.reward_redemptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  reward_id uuid NOT NULL,
  points_spent integer NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text,
  size text,
  shipping_name text NOT NULL,
  shipping_phone text NOT NULL,
  shipping_address_line1 text NOT NULL,
  shipping_address_line2 text,
  shipping_city text NOT NULL,
  shipping_state text NOT NULL,
  shipping_pincode text NOT NULL,
  admin_notes text,
  tracking_number text,
  courier_name text,
  requested_at timestamp with time zone DEFAULT now(),
  approved_at timestamp with time zone,
  shipped_at timestamp with time zone,
  delivered_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  cancelled_reason text,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT reward_redemptions_pkey PRIMARY KEY (id),
  CONSTRAINT reward_redemptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT reward_redemptions_reward_id_fkey FOREIGN KEY (reward_id) REFERENCES public.rewards(id)
);
CREATE TABLE public.ps_recruiter_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  requirement_id uuid,
  employer_id uuid NOT NULL,
  user_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'interest_sent'::text CHECK (status = ANY (ARRAY['interest_sent'::text, 'accepted'::text, 'declined'::text, 'withdrawn'::text, 'interview'::text, 'hired'::text, 'not_selected'::text])),
  fit_score integer,
  match_reasons jsonb DEFAULT '{}'::jsonb,
  unlocked_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  role_title text,
  sector text,
  notes text,
  employer_name text,
  employer_company text,
  candidate_masked_code text,
  candidate_trade text,
  candidate_service text,
  candidate_rank text,
  admin_notes text,
  CONSTRAINT ps_recruiter_requests_pkey PRIMARY KEY (id)
);
CREATE TABLE public.legal_aid_queries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  case_ref text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  profile text,
  service text,
  category text,
  situation text,
  urgency text,
  route text,
  qa_summary jsonb,
  contact_method text,
  mobile text,
  email text,
  consent boolean DEFAULT true,
  status text DEFAULT 'new'::text,
  admin_notes text,
  user_id uuid,
  CONSTRAINT legal_aid_queries_pkey PRIMARY KEY (id)
);
CREATE TABLE public.lc_exam_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  thumbnail_url text,
  CONSTRAINT lc_exam_categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.lc_reader_themes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  description text,
  is_default boolean NOT NULL DEFAULT false,
  is_system boolean NOT NULL DEFAULT false,
  tokens jsonb NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT lc_reader_themes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.lc_subjects (
  key text NOT NULL,
  label text NOT NULL,
  color_family text,
  thumbnail_url text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT lc_subjects_pkey PRIMARY KEY (key)
);